/**
 * TCG Machines API Demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryResult } from './queryResult';
import { ResponseError } from './responseError';
import { Card } from './card';


/**
 * @type APIResponse
 * @export
 */
export type APIResponse = QueryResult | ResponseError;

