/**
 * TCG Machines API Demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CardImageURIs } from './cardImageURIs';


export interface Card { 
    id: string;
    name: string;
    released_at: string;
    image_uris?: CardImageURIs;
}

