/**
 * TCG API Demo
 * A simple REST API for searching and listing trading game cards 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CardPrices } from './cardPrices';
import type { CardImageURIs } from './cardImageURIs';


export interface Card { 
    id: string;
    lang: string;
    name: string;
    uri: string;
    rarity: string;
    set_name: string;
    collector_number: number;
    released_at: string;
    games?: Array<string>;
    image_uris: CardImageURIs;
    nonfoil: boolean;
    foil: boolean;
    prices: CardPrices;
}

