/**
 * TCG Machines API Demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Card } from './card';


export interface QueryResponse { 
    /**
     * The total number of cards matching the search query
     */
    total: number;
    /**
     * A page of the cards matching the search query
     */
    data: Array<Card>;
    /**
     * A link to the next page of responses if one exists
     */
    next?: string;
    /**
     * A link to the previous page of responses if one exists
     */
    previous?: string;
}

