/**
 * TCG API Demo
 * A simple REST API for searching and listing trading game cards 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SortByParam = 'ASC' | 'DESC' | 'AUTO';

export const SortByParam = {
    Asc: 'ASC' as SortByParam,
    Desc: 'DESC' as SortByParam,
    Auto: 'AUTO' as SortByParam
};

