openapi: "3.0.0"
info:
  version: 1.0.0
  title: TCG Machines API Demo
  description: |
    A simple REST API for searching and listing trading game cards
  license:
    name: MIT
servers:
  - url: ''

tags: 
  - name: Search
    description: Search trading game cards
paths:
  /:
    get:
      summary: API Home
      description: The home endpoint for this API. Displays basic informational message
      operationId: apiHome
      tags:
        - Search
      responses:
        '200':
          description: A basic informational message about the search cards API
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/APIWelcome"
        '400':
          description: bad request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIResponseError"
        '500':
          description: backend server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIResponseError"
  /search:
    get:
      summary: List Cards
      description: Search for, and list trading game cards that match a search term
      operationId: searchCards
      tags:
        - Search
      parameters:
        - $ref: '#/components/parameters/searchTerm'
        - $ref: '#/components/parameters/orderBy'
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/page'

      responses:
        '200':
          description: A paged list of cards matching the search term
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/QueryResponse"
        '400':
          description: bad request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIResponseError"
        '500':
          description: backend server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIResponseError"

components:
  parameters: 
    searchTerm:
      in: query
      name: term
      description: The search term to find cards with
      required: true
      schema:
        $ref: "#/components/schemas/SearchTermParam"

    orderBy:
      in: query
      name: orderby
      description: On what property to order the matching cards. Default is `name`
      required: false
      schema:
        $ref: "#/components/schemas/OrderByParam"

    sortBy:
      in: query
      name: sortby
      required: false
      description: >
        The sort order of the returned cards. Default is `AUTO`
        Sort order:
          * `ASC` - Ascending, from A to Z
          * `DESC` - Descending, from Z to A
          * `AUTO` - Allow the system choose the most inuitive direction to sort.
      schema:
        $ref: "#/components/schemas/SortByParam"

    page:
      in: query
      name: page
      description: The page of the matching resultset to return. Default is `1`.
      required: false
      schema:
        $ref: "#/components/schemas/PageParam"

  schemas:

    PageParam:
      type: integer
      minimum: 1
      example: 1
      default: 1

    SearchTermParam:
      type: string
      maxLength: 50
      minLength: 3
      example: pokey

    OrderByParam:
      type: string
      enum:
        - name
        - released
      default: name
      example: name

    SortByParam:
      type: string
      enum:
        - ASC
        - DESC
        - AUTO
      default: AUTO
      example: AUTO

    APIWelcome:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          maxLength: 500

    CardImageURIs:
      type: object
      properties:
        small:
          type: string
          format: uri
        normal:
          type: string
          format: uri
        large:
          type: string
          format: uri
    
    Card:
      type: object
      required:
        - id
        - uri
        - name
        - lang
        - prices
        - foil
        - rarity
        - nonfoil
        - set_name
        - image_uris
        - released_at
        - collector_number
      properties:
        id:
          type: string
        lang:
          type: string
          maxLength: 5
        name:
          type: string
        uri:
          type: string
          format: uri
        rarity:
          type: string
        set_name:
          type: string
        collector_number:
          type: number
        released_at:
          type: string
          format: date
        games:
          type: array
          items:
            type: string
        image_uris:
          $ref: "#/components/schemas/CardImageURIs"
        nonfoil:
          type: boolean
        foil:
          type: boolean
        prices:
          type: object
          properties:
            usd:
              type: string
            eur:
              type: string

    Pagination:
      type: object
      properties:
        next:
          type: string
          description: A link to the next page of responses if one exists
        previous:
          type: string
          description: A link to the previous page of responses if one exists

    QueryResult:
      type: object
      required:
        - total
        - data
      properties:
        total: 
          type: integer
          description: The total number of cards matching the search query
        data:
          type: array
          maxItems: 175
          minItems: 0
          items:
            $ref: "#/components/schemas/Card"
          description: A page of the cards matching the search query
    
    QueryResponse:
      allOf:
        - $ref: "#/components/schemas/QueryResult"
        - $ref: "#/components/schemas/Pagination"
        

    APIError:
      type: object
      properties:
        message:
          type: string
        path:
          type: string

    APIResponseError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          maxLength: 150
          description: The error message from the server
        code:
          type: integer
          pattern: ^\d{3,3}$
        errors:
          type: array
          items:
            $ref: "#/components/schemas/APIError"